version: '3'
services:
 # Nginx server configuration   
  web:
    image: nginx:alpine
    container_name: webserver
    depends_on:
      - docker-mysql
      - php
    links:
      - docker-mysql
      - php
    volumes:
      - ./webcontent:/var/www/html
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - "80:80"
 # Php-fpm configuration
  php:
    build: ./
    image: php-fpm
    volumes:
      - ./webcontent:/var/www/html
      - ./php:/usr/local/etc/php/php
 # Mysql configuration
  docker-mysql:
    image: mysql:5.7
    container_name: docker-mysql
    restart: always
    environment:
        - MYSQL_DATABASE=oklaptop
        - MYSQL_ROOT_PASSWORD=laptopahmedk1
    ports:
        - "3306:3306"
    volumes:
        - ./dbdata:/var/lib/mysql
